# spark/Dockerfile
FROM bitnami/spark:latest

# Bu imaj Spark'ı standalone veya YARN üzerinde çalıştırmaya elverişlidir.
# Hadoop konfigürasyonuna erişmesi gerekiyorsa environment değişkenlerini ayarlayabilirsiniz.
