# kafka/Dockerfile
FROM bitnami/kafka:latest

# Yine Bitnami Kafka imajı. Config dosyalarını veya environment değişkenlerini
# docker-compose.yml'de tanımladığınız gibi verebilirsiniz.
# COPY server.properties /opt/bitnami/kafka/config/
